GET http://localhost:3000/api/user/getall?keyword=

###
GET http://localhost:3000/api/user/getbyid/1
###
POST http://127.0.0.1:3000/api/user/create
content-type: application/json

{
    "firstName":"huy",
    "lastName":"huy",
    "email":"huy1@gmail.com"
}
###
PUT http://localhost:3000/api/user/update/1
content-type: application/json

{
    "firstName":"lê huy",
    "lastName":"ne",
    "email":"duykhương@gmail.com"
}

###
DELETE http://localhost:3000/api/user/delete/4